installed_at: '2026-01-22T04:23:57+00:00'
skill_id: git/design-doc-mermaid
git_repo: https://github.com/SpillwaveSolutions/design-doc-mermaid
skill_path: /private/var/folders/tm/chrvt43s3rbdld20ghw1qtc40000gn/T/skilz-git-z56m74tj
git_sha: e13f987306d5cd7a34f541927a3228343dd90e45
skilz_version: 1.9.1
install_mode: copy
canonical_path: null
