installed_at: '2026-01-22T04:23:51+00:00'
skill_id: git/documentation-specialist
git_repo: https://github.com/SpillwaveSolutions/document-specialist-skill
skill_path: /private/var/folders/tm/chrvt43s3rbdld20ghw1qtc40000gn/T/skilz-git-6cvr5sou
git_sha: 4d50d302b9f40e8eafec72d78a86676cdd9511ac
skilz_version: 1.9.1
install_mode: copy
canonical_path: null
