installed_at: '2026-01-22T04:24:18+00:00'
skill_id: git/mastering-python-skill
git_repo: https://github.com/SpillwaveSolutions/mastering-python-skill-plugin
skill_path: /private/var/folders/tm/chrvt43s3rbdld20ghw1qtc40000gn/T/skilz-git-d0_33xax/skills/mastering-python-skill
git_sha: f01baebd4e6c160d3215c8333de407a87f46a385
skilz_version: 1.9.1
install_mode: copy
canonical_path: null
