# rulez_ui/Taskfile.yml - RuleZ UI (React/Tauri) Tasks
#
# Bun/Vite/Playwright/Tauri tasks for the desktop application.
# Parent can include this with: taskfile: ./rulez_ui/Taskfile.yml
#
# Quick start:
#   task --list           # Show available tasks
#   task dev              # Start dev server
#   task e2e              # Run Playwright E2E tests

version: '3'

vars:
  PORT: 1420

tasks:
  # ===========================================================================
  # Development Tasks
  # ===========================================================================

  default:
    desc: Show available tasks
    cmds:
      - task --list

  dev:
    desc: Start Vite dev server (browser mode)
    cmds:
      - bun run dev

  dev:tauri:
    desc: Start Tauri dev server (desktop mode)
    cmds:
      - bun run dev:tauri

  # ===========================================================================
  # Build Tasks
  # ===========================================================================

  build:
    desc: Build web assets
    cmds:
      - bun run build
    sources:
      - src/**/*.ts
      - src/**/*.tsx
      - src/**/*.css
      - index.html
      - vite.config.ts
    generates:
      - dist/**/*

  build:tauri:
    desc: Build Tauri desktop app
    cmds:
      - bun run build:tauri

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf dist
      - rm -rf src-tauri/target

  # ===========================================================================
  # Test Tasks
  # ===========================================================================

  test:
    desc: Run Bun unit tests
    cmds:
      - bun test

  test:watch:
    desc: Run unit tests in watch mode
    cmds:
      - bun test --watch

  # ===========================================================================
  # E2E Test Tasks
  # ===========================================================================

  e2e:
    desc: Run Playwright E2E tests
    cmds:
      - bunx playwright test

  e2e:headed:
    desc: Run E2E tests in headed mode
    cmds:
      - bunx playwright test --headed

  e2e:debug:
    desc: Run E2E tests in debug mode
    cmds:
      - bunx playwright test --debug

  e2e:ui:
    desc: Open Playwright UI mode
    cmds:
      - bunx playwright test --ui

  e2e:chromium:
    desc: Run E2E tests in Chromium only
    cmds:
      - bunx playwright test --project=chromium

  e2e:webkit:
    desc: Run E2E tests in WebKit only
    cmds:
      - bunx playwright test --project=webkit

  e2e:report:
    desc: Show Playwright test report
    cmds:
      - bunx playwright show-report

  playwright:install:
    desc: Install Playwright browsers
    cmds:
      - bunx playwright install

  playwright:install:deps:
    desc: Install Playwright browsers with dependencies
    cmds:
      - bunx playwright install --with-deps

  # ===========================================================================
  # Code Quality Tasks
  # ===========================================================================

  lint:
    desc: Run Biome linter
    cmds:
      - bun run lint

  lint:fix:
    desc: Fix linting issues
    cmds:
      - bun run lint:fix

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - bun run typecheck

  check:
    desc: Run all quality checks
    cmds:
      - task: typecheck
      - task: lint
      - task: test

  # ===========================================================================
  # CI Tasks
  # ===========================================================================

  ci:
    desc: Run full CI pipeline locally
    cmds:
      - task: check
      - task: build
      - task: e2e

  # ===========================================================================
  # Utility Tasks
  # ===========================================================================

  preview:
    desc: Preview production build
    deps: [build]
    cmds:
      - bun run preview

  install:
    desc: Install dependencies
    cmds:
      - bun install

  update:
    desc: Update dependencies
    cmds:
      - bun update
