installed_at: '2026-01-22T04:24:12+00:00'
skill_id: git/mastering-typescript
git_repo: https://github.com/SpillwaveSolutions/mastering-typescript-skill
skill_path: /private/var/folders/tm/chrvt43s3rbdld20ghw1qtc40000gn/T/skilz-git-_66pkw97/mastering-typescript
git_sha: 2f74a00f731f2ea4d48f45d852067a7be8efd0d1
skilz_version: 1.9.1
install_mode: copy
canonical_path: null
