installed_at: '2026-01-22T04:24:08+00:00'
skill_id: git/project-memory
git_repo: https://github.com/SpillwaveSolutions/project-memory
skill_path: /private/var/folders/tm/chrvt43s3rbdld20ghw1qtc40000gn/T/skilz-git-cqvu1yrl
git_sha: 7267697b6d7f960accfb4b9d6026a74a0b2fc5ff
skilz_version: 1.9.1
install_mode: copy
canonical_path: null
