installed_at: '2026-01-22T04:24:03+00:00'
skill_id: git/sdd
git_repo: https://github.com/SpillwaveSolutions/sdd-skill
skill_path: /private/var/folders/tm/chrvt43s3rbdld20ghw1qtc40000gn/T/skilz-git-7po3453m
git_sha: eba96064a34ae68c85c0a42186cf82da12ec5ef9
skilz_version: 1.9.1
install_mode: copy
canonical_path: null
