installed_at: '2026-01-22T04:23:45+00:00'
skill_id: git/mastering-git-cli
git_repo: https://github.com/SpillwaveSolutions/mastering-git-cli-agent-skill
skill_path: /private/var/folders/tm/chrvt43s3rbdld20ghw1qtc40000gn/T/skilz-git-yo7zhl_j/mastering-git-cli
git_sha: 95c0d49d8567bc02c94c82cf5f9da3f169f87c4e
skilz_version: 1.9.1
install_mode: copy
canonical_path: null
